repos:
  # Conventional Commits enforcement
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            build,
            chore,
            ci,
            docs,
            feat,
            fix,
            perf,
            refactor,
            revert,
            style,
            test,
            optional-scope,
          ]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=1000]

  # C++ formatting and linting
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: 336fdd7c3cab698ead0b1c95157b9e74d3906b62
    hooks:
      - id: clang-format
        args: [-i, --style=file, --no-diff]
        exclude: ^(build/|third-party/)
      - id: clang-tidy
        exclude: ^(build/|third-party/)

  # Python formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # Bash formatting
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
