name: Auto generate PR description

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-generate-pr-desc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Generate PR description
        uses: abhinavchadaga/claude-automated-pr-desc-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
