name: Run Unit Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang build-essential libssl-dev nlohmann-json3-dev libgtest-dev ninja-build wget

      - name: Cache Boost 1.88
        id: cache-boost
        uses: actions/cache@v4
        with:
          path: /usr/local
          key: boost-1.88.0-ubuntu-24.04-${{ hashFiles('.github/workflows/run_unit_tests.yml') }}

      - name: Install Boost 1.88
        if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
        run: |
          wget https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz
          tar -xzf boost_1_88_0.tar.gz
          cd boost_1_88_0
          ./bootstrap.sh
          sudo ./b2 install --prefix=/usr/local --with-system --with-url

      - name: Cache TA-Lib
        id: cache-talib
        uses: actions/cache@v4
        with:
          path: /usr/local
          key: talib-0.6.4-ubuntu-24.04-${{ hashFiles('.github/workflows/run_unit_tests.yml') }}

      - name: Install ta-lib from source
        if: ${{ steps.cache-talib.outputs.cache-hit != 'true' }}
        run: |
          wget https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib-0.6.4-src.tar.gz
          tar -xzf ta-lib-0.6.4-src.tar.gz
          cd ta-lib-0.6.4
          ./configure
          make -j $(nproc)
          sudo make install

      - name: Build and run unit tests
        run: ./run_tests.sh Release
