name: Run Unit Tests

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'run_unit_tests.yml'
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'run_unit_tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libssl-dev libboost-all-dev nlohmann-json3-dev libgtest-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build project
      run: cmake --build build

    - name: Build tests
      run: cmake --build build --target unit_tests

    - name: Run all unit tests
      run: |
        cd build
        ./tests/unit_tests
