name: Run Unit Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang build-essential libssl-dev libboost-all-dev nlohmann-json3-dev libgtest-dev ninja-build wget

      - name: Install ta-lib from source
        run: |
          wget https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib-0.6.4-src.tar.gz
          tar -xzf ta-lib-0.6.4-src.tar.gz
          cd ta-lib-0.6.4
          ./configure
          make -j $(nproc)
          sudo make install

      - name: Build and run unit tests
        run: ./run_tests.sh Release
