name: Run Unit Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ALPACA_API_KEY:  ${{ secrets.ALPACA_API_KEY }}
      ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libssl-dev libboost-all-dev nlohmann-json3-dev libgtest-dev ninja-build

    - name: Configure CMake
      run: cmake -S . -B build/Release -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja -DCMAKE_CXX_COMPILER=g++

    - name: Build project
      run: cmake --build build/Release

    - name: Run all unit tests
      run: |
        cd build/Release/tests
        ./unit_tests
