name: Run WebSocketSession Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libssl-dev
        
        # Install websocat
        curl -L -o websocat https://github.com/vi/websocat/releases/download/v1.14.0/websocat.x86_64-unknown-linux-musl
        chmod +x websocat
        sudo mv websocat /usr/local/bin

    - name: Generate test certificates
      run: |
        mkdir -p /tmp/certs
        
        # Generate private key
        openssl genrsa -out /tmp/certs/key.pem 2048
        
        # Generate certificate
        openssl req -new -x509 -key /tmp/certs/key.pem -out /tmp/certs/cert.pem -days 1 \
          -subj "/C=US/ST=Test/L=Test/O=Test/CN=localhost"
        
        # Create PKCS12 bundle
        openssl pkcs12 -export -out /tmp/certs/echo.p12 \
          -inkey /tmp/certs/key.pem -in /tmp/certs/cert.pem \
          -passout pass:pass123
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build project
      run: cmake --build build
      
    - name: Build tests
      run: cmake --build build --target unit_tests
    
    - name: Start WebSocket server
      run: |
        websocat -E --text \
                 --pkcs12-der=/tmp/certs/echo.p12 \
                 --pkcs12-passwd=pass123 \
                 wss-l:127.0.0.1:9001 mirror: &
        echo $! > websocat.pid
        sleep 10
    
    - name: Run WebSocketSession Test
      run: |
        cd build
        ./tests/unit_tests --gtest_filter="WebSocketSession.*"
    
    - name: Stop WebSocket server
      run: |
        if [ -f websocat.pid ]; then
          kill $(cat websocat.pid) || true
          rm websocat.pid
        fi